font_family Noto Sans Mono
font_size 11.0
scrollback_lines 10000
wheel_scroll_multiplier 3.0
enable_audio_bell no
confirm_os_window_close 0
copy_on_select no
strip_trailing_spaces smart
window_padding_width 8
background_opacity 1.0
foreground #e8e8ec
background #101014
selection_foreground #101014
selection_background #5ce1e6
cursor #f05adf
cursor_text_color #101014
url_color #5ce1e6
color0  #18181c
color1  #ed8796
color2  #a6da95
color3  #eed49f
color4  #8aadf4
color5  #f05adf
color6  #5ce1e6
color7  #cad3f5
color8  #5b6078
color9  #ed8796
color10 #a6da95
color11 #eed49f
color12 #8aadf4
color13 #f5bde6
color14 #8bd5ca
color15 #ffffff
map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard
map ctrl+shift+enter new_window_with_cwd
map ctrl+shift+t new_tab_with_cwd
